BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('student','teacher','worker','supervisor')),
  full_name TEXT NOT NULL,
  code TEXT, course TEXT, specialty TEXT, flow TEXT, faculty TEXT, group_name TEXT,
  subgroup TEXT, qualification TEXT, status TEXT DEFAULT 'Активен', department TEXT,
  title TEXT, work_type TEXT, position TEXT, supervisor_name TEXT, category TEXT,
  account_enabled INTEGER NOT NULL DEFAULT 1 CHECK (account_enabled IN (0, 1)),
  password_vault TEXT,
  developer_access INTEGER NOT NULL DEFAULT 0 CHECK (developer_access IN (0, 1))
);

CREATE TABLE IF NOT EXISTS admin_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  account_enabled INTEGER NOT NULL DEFAULT 1 CHECK (account_enabled IN (0, 1))
);

CREATE TABLE IF NOT EXISTS system_settings (
  setting_key TEXT PRIMARY KEY,
  setting_value TEXT NOT NULL
);
INSERT INTO system_settings (setting_key, setting_value) VALUES ('system_enabled', '1')
ON CONFLICT (setting_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS password_recovery_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('student','teacher','worker')),
  full_name TEXT NOT NULL,
  login TEXT NOT NULL,
  email TEXT NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','ready','resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS dpk_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  teacher_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  course TEXT, flow TEXT, group_name TEXT, date DATE, time TEXT, room TEXT
);

CREATE TABLE IF NOT EXISTS grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  lesson_id BIGINT REFERENCES dpk_lessons(id) ON DELETE CASCADE,
  grade INTEGER, comment TEXT, date DATE
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  lesson_id BIGINT REFERENCES dpk_lessons(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('present','absent','late')),
  date DATE
);

CREATE TABLE IF NOT EXISTS dpk_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  program_type TEXT NOT NULL DEFAULT 'ДПК',
  total_hours INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dpk_program_teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  group_name TEXT NOT NULL DEFAULT '',
  hours INTEGER DEFAULT 0,
  lecture_hours INTEGER DEFAULT 0,
  practice_hours INTEGER DEFAULT 0,
  lab_hours INTEGER DEFAULT 0,
  UNIQUE (program_id, group_name, teacher_id)
);

CREATE TABLE IF NOT EXISTS schedule_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT REFERENCES dpk_programs(id) ON DELETE SET NULL,
  teacher_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  group_name TEXT, room TEXT,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  time_start TEXT NOT NULL, time_end TEXT NOT NULL,
  program_name TEXT, date DATE, lesson_type TEXT, instructor_name TEXT, source TEXT
);

CREATE TABLE IF NOT EXISTS booking_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_name TEXT NOT NULL, requester_email TEXT NOT NULL, requester_phone TEXT,
  organization TEXT, room TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL,
  event_date DATE NOT NULL, time_start TEXT NOT NULL, time_end TEXT NOT NULL,
  recurrence TEXT NOT NULL DEFAULT 'once', recurrence_end DATE, event_url TEXT,
  attendees INTEGER DEFAULT 1, status TEXT NOT NULL DEFAULT 'requested',
  review_comment TEXT, reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS evaluation_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subgroup TEXT, missed_lectures INTEGER DEFAULT 0, missed_practicals INTEGER DEFAULT 0,
  admission TEXT, model_detail_level INTEGER, model_originality INTEGER,
  model_files_on_disk TEXT, bonus_render INTEGER DEFAULT 0, bonus_animation INTEGER DEFAULT 0,
  bonus_interesting_model INTEGER DEFAULT 0, has_guides TEXT, dashboard_blocks TEXT,
  chart_errors TEXT, bonus_design INTEGER DEFAULT 0, bonus_program_implementation INTEGER DEFAULT 0,
  defense_score INTEGER, total_score INTEGER, grade TEXT, fact TEXT,
  published INTEGER DEFAULT 0 CHECK (published IN (0, 1)),
  UNIQUE (program_id, student_id)
);

CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  class_type TEXT NOT NULL CHECK (class_type IN ('lecture','practice','lab')),
  class_number INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'present' CHECK (status IN ('present','absent')),
  UNIQUE (program_id, student_id, class_type, class_number)
);

CREATE TABLE IF NOT EXISTS attendance_lesson_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  group_name TEXT NOT NULL,
  class_type TEXT NOT NULL CHECK (class_type IN ('lecture','practice','lab')),
  class_number INTEGER NOT NULL,
  lesson_date DATE,
  UNIQUE (program_id, group_name, class_type, class_number)
);

CREATE TABLE IF NOT EXISTS attendance_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  group_name TEXT NOT NULL DEFAULT '', assignment_number INTEGER NOT NULL,
  UNIQUE (program_id, assignment_number)
);

CREATE TABLE IF NOT EXISTS attendance_assignment_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES attendance_assignments(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('completed','plus','minus')),
  UNIQUE (assignment_id, student_id)
);

CREATE TABLE IF NOT EXISTS dpk_program_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  group_name TEXT NOT NULL,
  UNIQUE (program_id, group_name)
);

CREATE TABLE IF NOT EXISTS dpk_program_evaluators (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE (program_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS dpk_teacher_lesson_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  group_name TEXT NOT NULL, class_type TEXT NOT NULL, class_number INTEGER NOT NULL,
  date DATE, room TEXT, time_start TEXT DEFAULT '09:00', time_end TEXT DEFAULT '10:30',
  UNIQUE (program_id, teacher_id, group_name, class_type, class_number)
);

CREATE TABLE IF NOT EXISTS user_sessions (
  sid VARCHAR NOT NULL PRIMARY KEY,
  sess JSON NOT NULL,
  expire TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expire ON user_sessions (expire);
CREATE INDEX IF NOT EXISTS idx_schedule_entries_room_date ON schedule_entries (room, date);
CREATE INDEX IF NOT EXISTS idx_schedule_entries_teacher ON schedule_entries (teacher_id);

COMMIT;
