CREATE TABLE IF NOT EXISTS attendance_lesson_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES dpk_programs(id) ON DELETE CASCADE,
  group_name TEXT NOT NULL,
  class_type TEXT NOT NULL CHECK (class_type IN ('lecture','practice','lab')),
  class_number INTEGER NOT NULL,
  lesson_date DATE,
  UNIQUE (program_id, group_name, class_type, class_number)
);

CREATE INDEX IF NOT EXISTS idx_attendance_lesson_dates_program_group
  ON attendance_lesson_dates (program_id, group_name);
